### ISSUE TITLE
Fix credential dependency slow requests

### ISSUE THREAD

**Issue by nrempel** [bcgov/von#177]
We think this is due to the lack of caching on domain endpoint lookups to the ledger.

The new version of von-anchor should include a built-in cache. We will need to add logic to clear the cache and try once again before failing in the case of a failed request to a cached domain endpoint.

**Comment by esune** [comment]
The issue was not with the agent's internal cache, but rather with `aiohttp` expecting both IPv4 and IPv6 DNS resolution service from the OpenShift cluster. IPv6 resolution would take a long time and the agent would be "blocked".

This commit allows to specify a TCP socket family to be used: https://github.com/PSPC-SPAC-buyandsell/von-x/commit/c8d91af1f5f3936d60ce3bf72deba1100c877bc2
Configurations in OpenShift have been updated to reflect the change, and the delay has now disappeared.
