### ISSUE TITLE
Load test the issuing of Credentials to TOB

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#20]

**Comment by WadeBarnes** [comment]
## Test setup:
- Environments:
  - [Ledger - DEV](http://159.89.115.24/)
    - Running an instance of [von-network](https://github.com/bcgov/von-network)
    - The ledger was reset prior to the tests.
  - [Permitify - DEV](https://console.pathfinder.gov.bc.ca:8443/console/project/devex-von-permitify-dev/overview)
    - bc-registries
    - city-of-surrey
    - fraser-valley-health-authority
    - liquor-control-and-licensing-branch
    - ministry-of-finance
    - worksafe-bc
    - The permitify services used for the test were configured to use a shared enterprise wallet to avoid the threading limitations of the local/virtual wallet.
    - Each service was scaled up to use 4 instances to process the requests.
    - Wallets were reset prior to the tests.
  - [TheOrgBook - Dev](https://console.pathfinder.gov.bc.ca:8443/console/project/devex-von-dev/overview)
    - Configured to use an enterprise wallet.
    - The tob-api service was configured to auto-scale from 1 to 4 instances.  The API was served using gunicron and the startup scripts were allowed to auto-determine the number of workers to run; typically 12, based on the logs.
    - Wallets and data were reset prior to the tests.
  - Data loader on development machine.
    - The lines in `loadClaims.py` associated with the Semaphores were all commented out to allow concurrent code execution.
    - Three processes (shells) running 4 threads each were use to load the data.  The processes were restarted any time they completed or exited due to an error.
    - Command used; `./load-all.sh --env dev --threads 4 --random`

## Summary 
A total of 329 Organizations and 1,043 credentials were loaded into TheOrgBook during the tests.  Several of the credentials loaded into the system can not be verified due to the errors encountered while storing them.

The load on the tob-api was significant enough to cause the service to auto-scale to it's maximum of 4 instances for much of the time.  Throughout the tests the services were dynamically scaling from 1 to 4 instances as the load varied due to the data loader scripts terminating and restarting.

During the tests, the von-network components and the permitify services did not appear to experience any internal errors.  All errors seemed to be isolated to the tob-api operations.

Following are a list of the types of errors were encountered numerous times throughout the testing;
- indy.error.IndyError: ErrorCode.PoolLedgerInvalidPoolHandle
- indy.error.IndyError: ErrorCode.CommonInvalidStructure
- indy.error.IndyError: ErrorCode.CommonIOError
- indy.error.IndyError: ErrorCode.CommonInvalidState

The errors, once encountered, placed the processes into a persistent error state.  Recovery from the condition required the service instance to be killed (allowing to to be restarted).

The errors occurred fairly frequently, but somewhat randomly.  Some service instances would encounter the errors right away, while others would run for long periods of time without issue. `ErrorLog2.txt` is an example of a tob-api service instance that encountered the error(s) early on.

The attached error logs provide samples of each of the errors along with logs from the period of time leading up to the errors.

**Comment by WadeBarnes** [comment]
[ErrorLog1.txt](https://github.com/bcgov/von/files/1955657/ErrorLog1.txt)
[ErrorLog2.txt](https://github.com/bcgov/von/files/1955658/ErrorLog2.txt)
[ErrorLog3.txt](https://github.com/bcgov/von/files/1955659/ErrorLog3.txt)

**Comment by WadeBarnes** [comment]
Handing over to @ianco to review the logs.  Tickets to resolve the issue(s) should be created in the appropriate locations (projects).

**Comment by swcurran** [comment]
@WadeBarnes - were you able to get any performance numbers, or were the errors too disruptive to get useful data?

**Comment by WadeBarnes** [comment]
The errors were too frequent and too disruptive to get any useful performance information.

**Comment by ianco** [comment]
ErrorLog3.txt - the error is thrown because the sdk can't de-serialize the claim into json.  Possibilities are:

- the claim is getting over-written in memory (python threading problem) 
- or something is getting over-written in the wallet (wallet can't handle multiple concurrent claim requests for the same issuer)

WARNING 2018-04-25 21:54:26,184 libindy 27 140010019198720 _indy_loop_callback: Function returned error 113
--- Logging error ---
Traceback (most recent call last):
  File "/opt/app-root/src/api/claimProcesser.py", line 284, in __StoreClaim
    await holder.store_claim(claim)
  File "/opt/app-root/src/.local/lib/python3.5/site-packages/von_agent/agents.py", line 1139, in store_claim
    None)  # rev_reg_json - TODO: revocation
  File "/opt/app-root/src/.local/lib/python3.5/site-packages/indy/anoncreds.py", line 472, in prover_store_claim
    prover_store_claim.cb)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
indy.error.IndyError: ErrorCode.CommonInvalidStructure

**Comment by ianco** [comment]
Note for the above - claim offer and claim request meta-data are stored in the holder's wallet (not a virtual wallet, because we can't determine the legal entity id), so there is only one per issuer.  However the error is thrown on the de-serialization of the claim (to json) not any crypto validation.

**Comment by ianco** [comment]
Re: PoolLedgerInvalidPoolHandle - no idea, other than a potential threading issue.  There is a potential race condition between creating and opening a wallet, if two threads are sharing the same object. The pool handle is created when the wallet is created, and then used when the wallet is opened (or when there are any sdk requests, such as saving a claim).

**Comment by ianco** [comment]
Re: CommonInvalidState - this seems to be related to the _seed_to_did() calculation, where we create a throw-away wallet just to convert the provided seed to a did.  (There is no public sdk api to fetch this value once it is saved, and no public method to do the conversion, other than to create the did in the wallet.)

I suggest we clean up the code to do the did calculation once, on startup, and then we can remove the "per request" calculation.

At the same time I suggest making sure we create the wallet, master secret, etc on startup and not per-request.  If we can reduce the redundant "per request" code we might reduce these kinds of errors.

**Comment by ianco** [comment]
Another observation - the hack I put in to fool indy-sdk into letting us open the same wallet multiple times is also fooling von-agent into trying to create the wallet multiple times.  In the wallet this is a "no-op", but in von-agent it's triggering the seed2did code on every request.

I suggest either:

- A single agent and/or wallet instance, shared by all the threads (would need to verify that everything is thread safe)
- Or a "pool" of agents and/or wallets, created on startup, to eliminate the per-request logic.

**Comment by WadeBarnes** [comment]
The results of the most recent test are likely not very useful.  On closer inspection all but one of the threads for the load data scripts encountered exceptions early on, so there was only one thread feeding data into TOB.

Further to that the loading process ended up failing due to a **indy.error.IndyError: ErrorCode.WalletNotFoundError**.  Error log attached.

[https://app.zenhub.com/files/98577443/c2a6e3d6-468a-459c-b24e-8d5059af940c/download](https://app.zenhub.com/files/98577443/c2a6e3d6-468a-459c-b24e-8d5059af940c/download)
