### ISSUE TITLE
Search by Credential

### ISSUE THREAD

**Issue by tgunderson** [bcgov/von#259]
Search by credential and add a geographic filters from the home page.
* Assume credential contains address / coordinate data

**Comment by swcurran** [comment]
Hi @tgunderson - we have plans for adding both those capabilities.  Two things that are holding it up.  We don't have addresses from BC Registries or other issuers yet - an understandable hesitation on the part of BC Registries.  Also, we need to get a UI/UX developer in place to help push some bigger ideas like that. #moreresources :-)

We do want to enable an API that puts a fixed filter on the main search so that an issuer can issue a pile of credentials, and then embed on their site a search that includes ONLY the companies that have the credentials that the issuer issues.

This will happen, but it will take a bit, driven by demand.

**Comment by swcurran** [comment]
@tgunderson - closing this issue as not fixed for now.  We can either reopen it in the future, or open new issues when we have some specific use cases to work with.  We'll get to it, but not for a bit.
