### ISSUE TITLE
Create up-to-date infrastructure model diagram

### ISSUE THREAD

**Issue by nrempel** [bcgov/von#33]
With the number of people collaborating on these projects, it would be beneficial to a have an up-to-date infrastructure diagram of how BC implements various components in its infrastructure. Especially relating to how BC Registries data is transformed and sent to von-x to enter the network.

What do you think @swcurran @jljordan42?

**Comment by swcurran** [comment]
This was documented recently in this Google Doc:

https://docs.google.com/document/d/1ITKyjMpwzp5NdOON2xP_3xsF4AuyPXK1mOIaQMqeVuU/edit#bookmark=id.7py42s8cqepa

We can put it into a purpose-built place so that it is the one place to go.  Need to think of that along with the rest of a roadmap for the applications we're creating.
