### ISSUE TITLE
Update OrgBook BC feedback email recipients

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#358]
Please change the feedback recipient from the current address (John Jordan, I think, but could be a group email) to Ian.armstrong@gov.bc.ca and swcurran@cloudcompass.ca.

Thanks

**Comment by swcurran** [comment]
@WadeBarnes assigning to you as I assume this is a configuration on the AVCR deployment.  Or it should be. :-)

**Comment by WadeBarnes** [comment]
Yes, it is a configuration.  Although I had to make some code updates (fixes) to fully support multiple recipients.  The fix is in `dev`.  All environments have been updated with the requested recipient list.  You're email is first in the list which means you will be the recipient of the feedback from `test` and `prod` until the fix is promoted to those environments.

**Comment by WadeBarnes** [comment]
Leaving this open until the updates are promoted all the way to `prod`, which should be soon.
