### ISSUE TITLE
Manage current and future TOB and BCReg PROD environments

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#90]
Provision a new environment and manage the environments to:

* Allow us to activate the environments as needed as we go through "Plan 37", and
* Have a designated long term PROD environment that is associated with the Sovrin Live Network.

This is going to take some data management. Left to Wade to figure out/ask for help on.

**Working Plan**
We have a set of environments to use as the temporary production environments, the ones we will connect to the BCovrin Ledger (hosted on Digital Ocean) and later toss.

These environments will be provisioned with the latest versions of our components (including the Postgres wallet storage, on the TOB side only), and all of the credentials will be reprocessed and reloaded.  There have been some significant enough changes in all of the components that we would benefit from another Technical Readiness launch.

**TheOrgBook-BC (bc-tob-prod-tmp)** (devex-bcgov-dac-dev)
- [X]  Clean out any existing resources
- [X] Initialize the project
- [x] Load the deployment configurations for `bc-tob-prod-tmp`, with settings based on `bc-tob-prod`.  **Use different seed values so we don't have collisions with the existing prod environment.**
- [x] Deploy the application components, tag images as `bc-tob-prod-tmp`
- [x] Verify everything starts up properly.

**BC Registries Agent (prod-tmp)** (devex-bcgov-dap-dev)
- [X] Clean out any existing resources
- [X] Initialize the project
- [x] Load the deployment configurations for `prod-tmp`, with settings based on `prod`.  **Use different seed values so we don't have collisions with the existing prod environment.**
- [x] Deploy the application components, tag images as `prod-tmp`
- [x] Verify connection to the BC Registries database
- [x] Initialize event database
- [x] Start the credential staging process
- [x] Start the credential posting process

**Comment by WadeBarnes** [comment]
I was able to use our regular [openshift-developer-tools](https://github.com/BCDevOps/openshift-developer-tools/tree/master/bin) script process to configure and manage the temporary environments using the profile feature plus a few additional overrides because there is only a single project environment.  I also added a command the the `openshift/manage` scripts to manage the deployment of images into those environments rather than pollute tools project with additional pipelines that are not permanent.

The scripts, settings, and parameters for these environments are being maintained on branches that can be cut once the environments are no longer needed.
- [TheOrgBook-BC (bc-tob-prod-tmp environment)](https://github.com/WadeBarnes/TheOrgBook/tree/bc-tob-prod-tmp)
-[BC Registries Agent (prod-tmp environment)](https://github.com/WadeBarnes/von-bc-registries-agent/tree/prod-tmp)
